name: MongoDB Push

on:
  push:
    paths:
      - '**/*'

jobs:
  push_to_mongodb:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to MongoDB
        run: |
          # Replace with your MongoDB connection details
          MONGODB_URI=$mongodb+srv://Ganesh:Ganesh@0808@cluster0.h1e3iec.mongodb.net/
          MONGODB_USERNAME=$Ganesh
          MONGODB_PASSWORD=$Ganesh@0808

          # Use a script or command to push files to MongoDB here
          # Example: mongofiles --uri "$MONGODB_URI" put path/to/file.ext
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
