name: Push Data to MongoDB
on:
  push:
    branches:
      - main  # Specify the branch you want to trigger this workflow on
jobs:
  push_data_to_mongodb:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your code repository
    - name: Set up MongoDB and import data
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Use the MongoDB URI secret
      run: |
        # Set your MongoDB connection URI as an environment variable
        export MONGODB_URI="${{ secrets.MONGODB_URI }}"
        # Path to your JSON data file
        JSON_FILE="./data.json"
        # MongoDB collection name
        COLLECTION_NAME="your-collection-name"
        # Check if the MongoDB URI is set
        if [ -z "$MONGODB_URI" ]; then
          echo "Error: MongoDB URI not set."
          exit 1
        fi
        # Check if the JSON file exists
        if [ ! -f "$JSON_FILE" ]; then
          echo "Error: JSON data file not found."
          exit 1
        fi
        # Push data to MongoDB
        mongoimport --uri "$MONGODB_URI" --collection "$COLLECTION_NAME" --file "$JSON_FILE"
        # Check the exit code of mongoimport
        if [ $? -eq 0 ]; then
          echo "Data imported successfully into MongoDB."
        else
          echo "Error: Failed to import data into MongoDB."
          exit 1
        fi
