name: Push JSON to MongoDB

on:
  push:
    paths:
      - 'gk.json'

jobs:
  push-to-mongodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker container
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        # Build the Docker image
        docker build -t my-mongodb-json-importer .

        # Run the Docker container with the MONGODB_URI environment variable
        docker run -e MONGODB_URI=$MONGODB_URI my-mongodb-json-importer

    - name: Error Handling
      run: |
        # Check if the previous step failed
        if [ $? -ne 0 ]; then
          echo "Error: Docker container failed to run."
          exit 1
        fi
