name: Push to MongoDB

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  push_to_mongodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MongoDB URI
      run: echo "MONGODB_URI=$MONGODB_URI" >> $GITHUB_ENV

    - name: Push to MongoDB
      run: |
        FILE_CONTENT=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3.raw" -L "https://raw.githubusercontent.com/${{ github.repository }}/main/data.json")
        echo "db.collection.insertOne({ content: '$FILE_CONTENT' })" > mongo_script.js
        mongo "$MONGODB_URI" --file mongo_script.js
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
