# GitHub Repository Details
github_username: Ganu456
github_repo: gh repo clone Ganu456/test1
github_json_file: data.json

# MongoDB Connection Details
mongodb_uri: "mongodb+srv://Ganesh:mRamX9lmMcTd8GUt@cluster0.h1e3iec.mongodb.net/"
mongodb_collection: data.json

# Temporary Directory
temp_dir: gh repo clone Ganu456/test1
