name: Push JSON to MongoDB

on:
  workflow_dispatch: # Trigger the workflow manually from the Actions tab.

jobs:
  push-json-to-mongodb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MongoDB tools
      run: sudo apt-get install -y mongodb-clients

    - name: Push JSON to MongoDB
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        # Download the JSON file from the repository
        wget https://raw.githubusercontent.com/${{ github.repository }}/main/data.json

        # Use `mongoimport` to push the JSON data to MongoDB
        mongoimport --uri="${MONGODB_URI}" --collection="your-collection-name" --file=data.json

        # Remove the downloaded JSON file
        rm data.json
